# Docker Compose for ARM development environment
version: '3.8'

services:
  voice-ai-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HUME_API_KEY=${HUME_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - voice-ai-backend
    restart: unless-stopped

volumes:
  redis_data:

networks:
  default:
    driver: bridge