# ARM64 Node Affinity Template - Fixed version without problematic deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: arm-node-config
  namespace: voice-ai
data:
  # ARM-specific optimization flags
  ARM_OPTIMIZATION: "true"
  CPU_AFFINITY: "arm64"
  MEMORY_OPTIMIZATION: "true"
  NEON_SIMD: "enabled"        # ARM NEON SIMD optimizations
  CACHE_LINE_SIZE: "64"       # ARM64 cache line size
  PAGE_SIZE: "4096"          # ARM64 page size

  # Voice processing optimizations for ARM
  AUDIO_BUFFER_SIZE: "4096"   # Optimized for ARM cache
  FFT_SIZE: "1024"           # ARM-optimized FFT size
  WORKER_THREADS: "4"        # ARM core count optimization

---
# ARM64 affinity template as ConfigMap for reference
apiVersion: v1
kind: ConfigMap
metadata:
  name: arm-affinity-template
  namespace: voice-ai
data:
  affinity.yaml: |
    # Use this affinity configuration in your deployments
    affinity:
      nodeAffinity:
        # Hard requirement for ARM64
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values: ["arm64"]

        # Prefer specific ARM node types
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values: ["arm64"]
        - weight: 80
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values: ["cax11", "cax21", "cax31", "cax41"]  # Hetzner ARM instance types

      # Pod anti-affinity for better distribution
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["voice-api"]
            topologyKey: kubernetes.io/hostname

    # Node selector as backup
    nodeSelector:
      kubernetes.io/arch: arm64

    # Tolerations for ARM-specific taints
    tolerations:
    - key: "arm64"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"