apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-api
  namespace: voice-ai
  labels:
    app: voice-api
    component: backend
    arch: arm64
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: voice-api
      component: backend

  template:
    metadata:
      labels:
        app: voice-api
        component: backend
        arch: arm64
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"

    spec:
      # ARM64 node affinity and selection
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: ["arm64"]

          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: ["arm64"]
          - weight: 80
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values: ["cax11", "cax21", "cax31", "cax41"]

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["voice-api"]
              topologyKey: kubernetes.io/hostname

      nodeSelector:
        kubernetes.io/arch: arm64

      tolerations:
      - key: "arm64"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      # Service account
      serviceAccountName: voice-api

      containers:
      - name: voice-api
        image: ghcr.io/malepatip/voice-ai/voice-api:latest
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: websocket
          containerPort: 8080
          protocol: TCP

        # ARM-optimized resource allocation
        resources:
          requests:
            cpu: "200m"           # ARM cores are efficient
            memory: "256Mi"       # Conservative start
            ephemeral-storage: "512Mi"
          limits:
            cpu: "800m"           # Burst capacity for voice processing
            memory: "1Gi"         # Memory for audio buffers
            ephemeral-storage: "2Gi"

        # Environment variables
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: WEBSOCKET_PORT
          value: "8080"

        # ARM optimization flags
        - name: ARM_OPTIMIZATION
          valueFrom:
            configMapKeyRef:
              name: arm-node-config
              key: ARM_OPTIMIZATION
        - name: NEON_SIMD
          valueFrom:
            configMapKeyRef:
              name: arm-node-config
              key: NEON_SIMD
        - name: AUDIO_BUFFER_SIZE
          valueFrom:
            configMapKeyRef:
              name: arm-node-config
              key: AUDIO_BUFFER_SIZE

        # Secrets
        - name: HUME_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: hume-api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: jwt-secret

        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1

        # Startup probe for slow ARM boot
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault

        # Volume mounts
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: audio-cache
          mountPath: /app/cache
        - name: logs
          mountPath: /app/logs

      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: audio-cache
        persistentVolumeClaim:
          claimName: audio-cache-pvc
      - name: logs
        emptyDir:
          sizeLimit: 500Mi

      # DNS policy for better resolution
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "2"
        - name: edns0

---
apiVersion: v1
kind: Service
metadata:
  name: voice-api-service
  namespace: voice-ai
  labels:
    app: voice-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: voice-api
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: websocket
    protocol: TCP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voice-api
  namespace: voice-ai
  labels:
    app: voice-api
    component: backend
automountServiceAccountToken: false

---
# Horizontal Pod Autoscaler for cost-effective scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voice-api-hpa
  namespace: voice-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voice-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60